name: tritac3d
description: "3D tik-tak-toe game"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  vector_math: ^2.1.4
  vibration: ^2.0.1
  flutter_svg: ^2.0.16
  flutter_webrtc: ^0.12.4
  back_button_interceptor: ^8.0.3
  firebase_core: ^3.9.0
  firebase_database: ^11.2.0
  flutter_native_splash: ^2.4.4
  fluttertoast: ^8.2.10
  # google_mobile_ads: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false

  assets:
    - assets/icons/icon_internetsearch.svg
    - assets/icons/icon_crown.svg
    - assets/icons/icon_grid.svg
    - assets/icons/icon_abc.svg
    - assets/icons/icon_addcircle.svg
    - assets/icons/icon_arrowup.svg
    - assets/icons/icon_arrowdown.svg
    - assets/icons/icon_lan.svg
    - assets/icons/icon_server.svg
    - assets/icons/icon_arrowback.svg
    - assets/images/image_background.png

  fonts:
    - family: Jersey10
      fonts:
        - asset: assets/fonts/Jersey10-Regular.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Italic-VariableFont.ttf
          style: italic
        - asset: assets/fonts/Inter-VariableFont.ttf
        - asset: assets/fonts/Inter_28pt-Black.ttf
          weight: 900