// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB337HjxsWsr_ccS4gGTPBNUGGuiy3RoOs',
    appId: '1:627481458023:web:ebd60dfdeebd51cbd82bc2',
    messagingSenderId: '627481458023',
    projectId: 'tritac3d',
    authDomain: 'tritac3d.firebaseapp.com',
    databaseURL:
        'https://tritac3d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tritac3d.firebasestorage.app',
    measurementId: 'G-SP0E42463V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9eTTcCPZbmWbbwcpmpm86jxRZvIsErx8',
    appId: '1:627481458023:android:62a856535ddcc6d3d82bc2',
    messagingSenderId: '627481458023',
    projectId: 'tritac3d',
    databaseURL:
        'https://tritac3d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tritac3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOhLzcMWG7dYrMff_YRe5E5z8heaPTmgo',
    appId: '1:627481458023:ios:844c0759980397c5d82bc2',
    messagingSenderId: '627481458023',
    projectId: 'tritac3d',
    databaseURL:
        'https://tritac3d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tritac3d.firebasestorage.app',
    iosBundleId: 'com.tritac3d.app',
  );
}
